### ISSUE TITLE
Prepare Presentation for CA Conference

### ISSUE THREAD

**Issue by XeniaGabriela** [Quant-X-Security-Coding-GmbH/QAA_Condition_Number#1]
Your design, Peter!

We will align middle of September for a QA in our regular meeting.

Looking forward to hearing your draft:-)

**Comment by PeterNo-ai** [comment]
Planned Contents for ca. 60 min:
A Symmetric block ciphers, eg. AES (short)
B The Quantum Algorithm QAA presented through example 3.5 in ChenGao
C Optional: Quant-X Sec is developing a Quantum Algorithm for computing the complexity of the QAA on AES

**Comment by XeniaGabriela** [comment]
Presentation went well, feedback from BSI experts is incorporated to README.md
